server:
  port: 8081
  servlet:
    context-path: /medical

spring:
  application:
    name: medical-design

  datasource:
    url: jdbc:mysql://localhost:3306/medical_design_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.medical.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.example.medical: DEBUG
    org.springframework.web: INFO